export const notifications = [
  {
    id: 1,
    title: "Agent Lisa Thompson - Positive Customer Feedback Call",
    message: "We received an amazing customer feedback praising Lisa Thompson's helpful and friendly demeanor during a recent support call. Her dedication to customer satisfaction is truly commendable!",
    date: "2024-05-15 09:00:00",
    isRead: false,
  },
  {
    id: 2,
    title: "Agent Mark Wilson - Schedule Change Request",
    message: "Mark Wilson has requested a schedule change for next week due to a personal commitment. Please review the request and provide a response by the end of the day.",
    date: "2024-05-15 14:30:00",
    isRead: false,
  },
  {
    id: 3,
    title: "Agent Training - Customer Service Skills",
    message: "All agents, including Emily Davis and Michael Thompson, are invited to attend a training session on advanced customer service skills. The session will be conducted by our experienced trainer, Sarah Johnson.",
    date: "2024-05-15 11:15:00",
    isRead: false,
  },
  {
    id: 4,
    title: "Agent Andrew Martinez - Exemplary Handling of a Difficult Customer",
    message: "Andrew Martinez demonstrated exceptional patience and problem-solving skills while handling a challenging customer situation yesterday. His calm and professional approach turned a potentially negative experience into a positive one.",
    date: "2024-05-15 16:45:00",
    isRead: false,
  },
  {
    id: 5,
    title: "Agent Jessica Patel - Top Performer of the Month",
    message: "Congratulations to Jessica Patel for being recognized as the top performer of the month! Her consistent high-quality work and commitment to customer satisfaction have set a great example for the entire team.",
    date: "2024-05-12 10:00:00",
    isRead: false,
  },
  {
    id: 6,
    title: "Agent David Kim - Assistance Required",
    message: "David Kim is currently assisting a customer with a complex technical issue. If any other agent with expertise in this area is available, please reach out to David and provide support.",
    date: "2024-05-11 13:20:00",
    isRead: false,
  },
  {
    id: 7,
    title: "Agent Emily Rodriguez - Vacation Request Approved",
    message: "Emily Rodriguez's vacation request for the first week of next month has been approved. Please ensure that her shifts are covered and the team is notified of the updated schedule.",
    date: "2024-05-10 09:30:00",
    isRead: false,
  },
  {
    id: 8,
    title: "Agent Michael Chen - Successful Upselling",
    message: "Michael Chen successfully upsold our premium service package to three customers today. His excellent communication skills and product knowledge have contributed to increased revenue for the company.",
    date: "2024-05-09 15:00:00",
    isRead: false,
  },
  {
    id: 9,
    title: "Agent Sarah Davis - Customer Complaint Resolved",
    message: "Sarah Davis successfully resolved a customer complaint that had been escalated to the management team. Her empathy, active listening, and problem-solving abilities helped turn a dissatisfied customer into a loyal one.",
    date: "2024-05-08 11:45:00",
    isRead: false,
  },
  {
    id: 10,
    title: "Agent Training - Effective Time Management",
    message: "All agents, including Mark Wilson and Lisa Thompson, are required to attend a training session on effective time management techniques. The session aims to help agents optimize their productivity and manage their workload efficiently.",
    date: "2024-05-07 14:00:00",
    isRead: false,
  },
  {
    id: 11,
    title: "Agent Jessica Martinez - Outstanding First Week",
    message: "Jessica Martinez, our newly hired agent, has had an outstanding first week on the job. Her quick learning ability and enthusiasm have impressed the entire team. Keep up the great work, Jessica!",
    date: "2024-05-06 10:15:00",
    isRead: false,
  },
  {
    id: 12,
    title: "Agent Andrew Thompson - Mentoring Session",
    message: "Andrew Thompson has volunteered to conduct a mentoring session for our new batch of agents. His expertise and guidance will be invaluable in helping them navigate their roles and responsibilities.",
    date: "2024-05-05 13:30:00",
    isRead: false,
  },
  {
    id: 13,
    title: "Agent Emily Wilson - Customer Appreciation",
    message: "A customer sent a heartfelt email appreciating Emily Wilson's exceptional service and going above and beyond to assist them. Emily's dedication to customer satisfaction is truly inspiring!",
    date: "2024-05-04 16:00:00",
    isRead: false,
  },
  {
    id: 14,
    title: "Agent Michael Patel - Performance Improvement Recognized",
    message: "Michael Patel has shown significant improvement in his performance over the past month. His hard work and commitment to self-development have not gone unnoticed. Keep up the excellent progress, Michael!",
    date: "2024-05-03 09:45:00",
    isRead: false,
  },
  {
    id: 15,
    title: "Agent Sarah Kim - Knowledge Sharing Session",
    message: "Sarah Kim will be hosting a knowledge sharing session next week to discuss best practices for handling common customer inquiries. All agents are encouraged to attend and contribute their insights.",
    date: "2024-05-02 11:30:00",
    isRead: false,
  },
  {
    id: 16,
    title: "Agent David Rodriguez - Collaboration Appreciated",
    message: "David Rodriguez went out of his way to assist a colleague who was facing a challenging customer issue. His willingness to collaborate and share his expertise demonstrates the true spirit of teamwork.",
    date: "2024-05-01 14:15:00",
    isRead: false,
  },
  {
    id: 17,
    title: "Agent Sarah Johnson - Outstanding Performance",
    message: "Congratulations to Sarah Johnson for achieving the highest customer satisfaction score this week! Her exceptional communication skills and problem-solving abilities have greatly contributed to our team's success.",
    date: "2024-02-16 10:30:00",
    isRead: false,
  },
  {
    id: 18,
    title: "Agent Training Session - Mandatory Attendance",
    message: "All agents, including David Martinez and Emily Thompson, are required to attend the upcoming training session on effective communication techniques. The session will be held next Monday at 2:00 PM in the conference room.",
    date: "2024-05-16 14:45:00",
    isRead: false,
  },
  {
    id: 19,
    title: "Agent Michael Patel - Leave Request Approved",
    message: "Michael Patel's leave request for next week has been approved. Please ensure that his shifts are covered and the team is informed about the updated schedule.",
    date: "2024-05-16 09:00:00",
    isRead: false,
  },
  {
    id: 20,
    title: "Agent Jessica Rodriguez - Customer Compliment",
    message: "We received a glowing compliment from a customer appreciating Jessica Rodriguez's exceptional service and patience during a complex issue. Great job, Jessica! Keep up the excellent work.",
    date: "2024-05-15 16:15:00",
    isRead: false,
  },
  {
    id: 21,
    title: "Agent Andrew Kim - Performance Improvement Plan",
    message: "Andrew Kim has been placed on a performance improvement plan due to recent challenges in meeting the required metrics. The supervisor will work closely with Andrew to provide guidance and support to help him improve his performance.",
    date: "2024-05-15 11:20:00",
    isRead: false,
  },
  {
    id: 22,
    title: "Agent Jessica Rodriguez - Performance Improvement Plan",
    message: "Andrew Kim has been placed on a performance improvement plan due to recent challenges in meeting the required metrics. The supervisor will work closely with Andrew to provide guidance and support to help him improve his performance.",
    date: "2024-05-15 11:20:00",
    isRead: false,
  },
  {
    id: 23,
    title: "Positive Customer Feedback",
    message: "We received a glowing review from a satisfied customer, praising Agent Emily Thompson for her outstanding customer service and problem-solving skills during their recent interaction.",
    date: "2024-05-15 09:15:00",
    isRead: false,
  },
  {
    id: 24,
    title: "Training Session Reminder",
    message: "Reminder: All customer service agents are required to attend the 'Effective Communication Techniques' training session scheduled for tomorrow at 2:00 PM in the main conference room.",
    date: "2024-05-16 16:30:00",
    isRead: false,
  },
  {
    id: 25,
    title: "Agent Availability Update",
    message: "Agent Michael Johnson will be out of the office next week due to a scheduled vacation. Please update the schedules and agent availability accordingly.",
    date: "2024-05-16 11:45:00",
    isRead: false,
  },
  {
    id: 26,
    title: "High Call Volume Alert",
    message: "Our customer service department is currently experiencing a high volume of incoming calls. All available agents are requested to log in and assist with the call queue to ensure prompt customer support.",
    date: "2024-05-16 14:20:00",
    isRead: false,
  },
  {
    id: 27,
    title: "Bad Sentiment during ongoing call",
    message: "Mark Wilson has requested a schedule change for next week due to a personal commitment. Please review the request and provide a response by the end of the day.",
    date: "2024-05-20 14:30:00",
    isRead: false,
  },
  {
    id: 28,
    title: "Flight Management queue is too long",
    message: "Please rearrange your agents to manage the long queue of Flight Management",
    date: "2024-05-20 14:30:00",
    isRead: false,
  },
  {
    id: 29,
    title: "Lost bagagge queue is too long",
    message: "Please rearrange your agents to manage the long queue of Lost Baggage",
    date: "2024-05-22 14:30:00",
    isRead: false,
  },
];